/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BotChannelEmailObservation struct {

	// The ID of the Email Integration for a Bot Channel.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type BotChannelEmailParameters struct {

	// The name of the Bot Resource this channel will be associated with. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/apis/botservice/v1beta1.BotChannelsRegistration
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	BotName *string `json:"botName,omitempty" tf:"bot_name,omitempty"`

	// Reference to a BotChannelsRegistration in botservice to populate botName.
	// +kubebuilder:validation:Optional
	BotNameRef *v1.Reference `json:"botNameRef,omitempty" tf:"-"`

	// Selector for a BotChannelsRegistration in botservice to populate botName.
	// +kubebuilder:validation:Optional
	BotNameSelector *v1.Selector `json:"botNameSelector,omitempty" tf:"-"`

	// The email address that the Bot will authenticate with.
	// +kubebuilder:validation:Required
	EmailAddress *string `json:"emailAddress" tf:"email_address,omitempty"`

	// The email password that the Bot will authenticate with.
	// +kubebuilder:validation:Required
	EmailPasswordSecretRef v1.SecretKeySelector `json:"emailPasswordSecretRef" tf:"-"`

	// The supported Azure location where the resource exists. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// The name of the resource group in which to create the Bot Channel. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/upbound/provider-azure/apis/azure/v1beta1.ResourceGroup
	// +kubebuilder:validation:Optional
	ResourceGroupName *string `json:"resourceGroupName,omitempty" tf:"resource_group_name,omitempty"`

	// Reference to a ResourceGroup in azure to populate resourceGroupName.
	// +kubebuilder:validation:Optional
	ResourceGroupNameRef *v1.Reference `json:"resourceGroupNameRef,omitempty" tf:"-"`

	// Selector for a ResourceGroup in azure to populate resourceGroupName.
	// +kubebuilder:validation:Optional
	ResourceGroupNameSelector *v1.Selector `json:"resourceGroupNameSelector,omitempty" tf:"-"`
}

// BotChannelEmailSpec defines the desired state of BotChannelEmail
type BotChannelEmailSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BotChannelEmailParameters `json:"forProvider"`
}

// BotChannelEmailStatus defines the observed state of BotChannelEmail.
type BotChannelEmailStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BotChannelEmailObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BotChannelEmail is the Schema for the BotChannelEmails API. Manages a Email integration for a Bot Channel
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type BotChannelEmail struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BotChannelEmailSpec   `json:"spec"`
	Status            BotChannelEmailStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BotChannelEmailList contains a list of BotChannelEmails
type BotChannelEmailList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BotChannelEmail `json:"items"`
}

// Repository type metadata.
var (
	BotChannelEmail_Kind             = "BotChannelEmail"
	BotChannelEmail_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BotChannelEmail_Kind}.String()
	BotChannelEmail_KindAPIVersion   = BotChannelEmail_Kind + "." + CRDGroupVersion.String()
	BotChannelEmail_GroupVersionKind = CRDGroupVersion.WithKind(BotChannelEmail_Kind)
)

func init() {
	SchemeBuilder.Register(&BotChannelEmail{}, &BotChannelEmailList{})
}
