apiVersion: botservice.azure.upbound.io/v1beta1
kind: BotChannelDirectLineSpeech
metadata:
  annotations:
    meta.upbound.io/example-id: botservice/v1beta1/botchanneldirectlinespeech
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    botNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    cognitiveServiceAccessKeySecretRef:
      key: attribute.primary_access_key
      name: example-cognitive-account
      namespace: upbound-system
    cognitiveServiceLocation: ${azurerm_cognitive_account.example.location}
    location: global
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: botservice.azure.upbound.io/v1beta1
kind: BotChannelsRegistration
metadata:
  annotations:
    meta.upbound.io/example-id: botservice/v1beta1/botchanneldirectlinespeech
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: global
    microsoftAppId: ${data.azurerm_client_config.current.client_id}
    name: example-bcr
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: F0

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: botservice/v1beta1/botchanneldirectlinespeech
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

