apiVersion: web.azure.upbound.io/v1beta1
kind: LinuxFunctionAppSlot
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/linuxfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    functionAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example-linux-function-app-slot
    siteConfig:
    - {}
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: web.azure.upbound.io/v1beta1
kind: LinuxFunctionApp
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/linuxfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    name: example-linux-function-app
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    servicePlanId: ${azurerm_service_plan.example.id}
    siteConfig:
    - {}
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/linuxfunctionappslot
  labels:
    testing.upbound.io/example-name: linux-web-app-r-group-label
  name: linux-web-app-r-group
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: web/v1beta1/linuxfunctionappslot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

